include: /.gitlab/.gitlab-ci.compose.yml

image: dtzar/helm-kubectl:3.3.0

stages:
  - build
  - test
  - deploy
  - check

before_script: &common_before
  - kubectl create secret docker-registry registry-token -n api
    --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USER --docker-password=$CI_REGISTRY_TOKEN --dry-run -o yaml | kubectl apply -f -
  - kubectl create secret generic mongo-auth -n api
    --from-literal=MONGO_USER=$MONGO_USER --from-literal=MONGO_PASSWORD=$MONGO_PASSWORD --dry-run -o yaml | kubectl apply -f -
  - apk add gettext


# build stage steps:

api.build:
  image: docker/compose:1.25.0
  services:
    - docker:18.09-dind
  stage: build
  tags:
    - k8s
    - api
  variables:
    DOCKER_HOST: tcp://localhost:2375
  allow_failure: true
  except:
    changes:
      - "*.md"
  before_script:
    - docker version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
  script:
    - docker-compose build
  after_script:
    - docker-compose push

# test stage steps:

api.test:
  stage: test
  tags:
    - k8s
    - api
  except:
    changes:
      - "*.md"
  before_script:
    - printf "\e[32mTODO"
  script:
    - echo -e "\e[33mYou should implement test... \e[91mI am serisous, dude - \e[1mTESTS ARE IMPORTANT!"

# deploy stage steps:

users.deploy.k8s:
  stage: deploy
  tags:
    - k8s
    - api
  only:
    changes:
      - user-service/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  before_script:
    - *common_before
    - kubectl create secret generic mail-auth -n api
      --from-literal=MAIL_SERVER=$MAIL_SERVER --from-literal=MAIL_ADDRESS=$MAIL_ADDRESS --from-literal=MAIL_PASSWORD=$MAIL_PASSWORD --dry-run -o yaml | kubectl apply -f -
    - envsubst < config/config.$ENV.yaml > config.yaml && kubectl create configmap provider-bot.config -n bot
      --from-file=config.yaml=config.yaml --dry-run -o yaml | kubectl apply -f -
  script:
    - helm upgrade --install -n api users-service user-service/users-chart