apiVersion: v2
name: provider-bot
description: Web worker-service dedicated for reference models providing through web scraping & data analysis pipeline
type: application
version: 0.1.0
appVersion: 1.0.0
sources:
  - https://github.com/timoth-y/kicksware-provider-bot.git
maintainers:
  - name: Timothy Yalugin