project: kicksware
component: provider-bot
nameOverride: ""
fullnameOverride: ""
replicaCount: 1

image:
  registry: registry.kicksware.com
  repository: provider-bot
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    - host: bot.kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: provider-bot
          port: 8080
          scheme: http

volumes:
  - name: backup
    persistent:
      claim: provider-bot-backupclaim
      storageClass: nfs
      size: 1Gi
      accessModes:
        - ReadWriteOnce
    mountPath: /root/backup
  - name: storage
    persistent:
      claim: provider-bot-storageclaim
      storageClass: nfs # TODO use existing gluster-fs volume
      size: 1Gi
      accessModes:
        - ReadWriteOnce
    mountPath: /root/storage/images

resources: {} # TODO set limit

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  dockerRegistry: registry-token
  mounts:
    - name: mongo-tls
      mountPath: /root/certs/mongo

config:
  environment: k8s
  configMountPath: /root/config/config.yaml

