stages:
  - deploy

variables:
  SOURCE_DIR: /source/repos/$CI_PROJECT_NAME

bot.deploy.compose:
  image:
    name: docker/compose:1.25.0
  services:
    - docker:stable-dind
  stage: deploy
  tags:
    - compose
    - bot
  except:
    kubernetes: active
  before_script:
    - apk add make
  script:
    - make bot
